name: Test

on: [push]

jobs:
  test_cpython:
    name: CPython ${{ matrix.py }} for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        py: [3.7]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Rust
        run: |
          wget --https-only --secure-protocol=TLSv1_2 -O rustup-init.sh https://sh.rustup.rs
          sh ./rustup-init.sh --default-toolchain nightly -y -v
          echo ::add-path::$HOME/.cargo/bin
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.py }}
          architecture: x64
      - name: Install Pipenv
        run: |
          pip3 install --user pipenv
          echo ::add-path::$HOME/.local/bin
      - name: Setup Virtualenv
        run: |
          mkdir -p $VIRTUAL_ENV
          pipenv --python ${{ matrix.py }} install --dev
          echo ::add-path::$VIRTUAL_ENV
          echo ::set-env name=VIRTUAL_ENV::$VIRTUAL_ENV
        env:
          VIRTUAL_ENV=$HOME/hyperjson-venv
      - name: Setup Hyperjson
        run: pipenv run maturin develop --release -i python${{ matrix.py }}
      - name: Run Tests
        run: pipenv run pytest tests
      - name: Benchmarks
        run: pipenv run pytest benchmarks --compare
