name: Test

on: [push]

jobs:
  test_cpython:
    name: CPython ${{ matrix.py }} for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        py: [3.7]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Python ${{ matrix.py }}
        uses: actions/setup-python@v1
          with:
            python-version: ${{ matrix.py }}
            architecture: x64
      - name: Install Rust
        run: |
          wget --https-only --secure-protocol=TLSv1_2 -O rustup-init.sh https://sh.rustup.rs
          sh ./rustup-init.sh --default-toolchain nightly -y -v
     
      - name: Setup Pipenv
        run: sudo pip${{ matrix.py }} install pipenv

      - name: Run Tests
        run: make test
