name: Test

on: [push]

jobs:
  test:
    name: Test on python ${{ matrix.py }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py: [3.7] 
    container:
      image: quay.io/python-devs/ci-image:master
      env: 
        PATH: "/home/runner/.cargo/bin:/home/runner/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        LC_ALL: C.UTF-8
        LANG: C.UTF-8
      options: --user runner
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Rust
        run: |
          set -x
          wget --https-only --secure-protocol=TLSv1_2 -O rustup-init.sh https://sh.rustup.rs
          chmod +x ./rustup-init.sh
          ./rustup-init.sh --default-toolchain nightly -y -v
        working-directory: /tmp

      - name: Setup Pipenv
        run: pip${{ matrix.py }} install --user pipenv

      - name: Run Tests
        run: make test
