name: Test

on: [push]

jobs:
  test_cpython:
    name: CPython ${{ matrix.py }} for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        py: [3.5, 3.6, 3.7]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Rust
        run: |
          wget --https-only --secure-protocol=TLSv1_2 -O rustup-init.sh https://sh.rustup.rs
          sh ./rustup-init.sh --default-toolchain nightly -y -v
          echo ::add-path::$HOME/.cargo/bin
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.py }}
          architecture: x64
      - name: Install Pipenv
        run: |
          pip3 install --user pipenv
          echo ::add-path::$HOME/.local/bin
      - name: Setup Virtualenv
        run: |
          # squelch the warning
          sed -i -e 's/python_version.*/python_version = "${{matrix.py}}"/g' Pipfile
          pipenv --python ${{ matrix.py }} install --dev --skip-lock
          echo ::add-path::$(dirname $(pipenv run which pip 2>/dev/null))
      - name: Setup Hyperjson
        run: |
          pipenv install maturin
          pipenv run maturin develop --release
      - name: Run Tests
        run: pipenv run pytest tests
      - name: Benchmarks
        run: |
          mkdir bench_out
          pipenv run pytest benchmarks --compare --benchmark-json bench_out/report.json
          bzip2 bench_out/report.json
      - name: Generate Benchmark Reports
        if: matrix.os == 'ubuntu-latest'
        run: pipenv run python benchmarks/histogram.py bench_out/report.json bench_out
      - name: Upload Benchmark Results
        uses: actions/upload-artifact@master
        if: matrix.os == 'ubuntu-latest'
        with:
          name: benchmarks
          path: bench_out
