name: Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        py: ['3.5', '3.6', '3.7', 3.8', '3.9'] 
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust
        container:
          image: quay.io/python-devs/ci-image:master
          env: 
            PATH: "$HOME/.local/bin:$HOME/.cargo/bin:$PATH"
            LC_ALL: C.UTF-8
            LANG: C.UTF-8
        run: |
          # there is no curl, only wget
          wget --https-only --secure-protocol=TLSv1_2 -O rustup-init.sh https://sh.rustup.rs
          sh rustup-init.sh --default-toolchain nightly -y -v
          
        with:
          entrypoint: /bin/sh {0}
      - name: Setup Pipenv
        run: |
          pip${{ matrix.py }} install --user pipenv

      - name: Run Tests
        run: |
          make test
